<?php
/**
 * Application-wide configuration
 */

// Base URL -- reads APP_BASE_URL from the environment (set this in
// Render), falling back to the XAMPP htdocs path for local dev.
// No trailing slash.
define('BASE_URL', rtrim(getenv('APP_BASE_URL') ?: 'http://localhost/faculty201', '/'));

// All dates/times shown or generated by PHP are Philippine time,
// whatever the server's php.ini default is (XAMPP ships Europe/Berlin).
date_default_timezone_set('Asia/Manila');

// Filesystem paths
define('ROOT_PATH', dirname(__DIR__));
define('TEMP_SCAN_PATH', ROOT_PATH . '/temp_scans');   // holds scans while the faculty member previews them, before upload
define('UPLOADS_PATH', ROOT_PATH . '/uploads');         // final filed repository: uploads/{faculty_id}/{document_type}/

// Allowed scan file types
define('ALLOWED_MIME_TYPES', ['image/jpeg', 'image/png', 'image/webp', 'application/pdf']);
define('ALLOWED_EXTENSIONS', ['jpg', 'jpeg', 'png', 'webp', 'pdf']);
define('MAX_UPLOAD_BYTES', 10 * 1024 * 1024); // 10MB

// Keyword hints used by the OCR classifier (OcrProcessor.php) to
// auto-categorize an upload. Matched case-insensitively as whole words
// against the extracted text; multi-word phrases count for more than
// single words because they're more specific. Keys must match
// document_categories() in includes/functions.php.
define('DOCUMENT_TYPE_KEYWORDS', [
    'PDS'         => ['personal data sheet', 'cs form no. 212', 'cs form 212', 'pds', 'family background', 'civil service eligibility',
                      'voluntary work', 'learning and development', 'name extension', 'residential address'],
    'Certificate' => ['certificate', 'certificate of completion', 'certificate of attendance', 'certificate of participation',
                      'certificate of appreciation', 'certificate of recognition', 'seminar', 'webinar', 'training', 'workshop',
                      'participant', 'awarded to', 'is hereby given', 'has attended', 'has participated'],
    'Diploma'     => ['diploma', 'conferred', 'conferred the degree', 'degree of', 'bachelor of', 'master of', 'doctor of',
                      'rights and privileges', 'board of regents', 'board of trustees'],
    'TOR'         => ['transcript of records', 'official transcript', 'transcript', 'tor', 'units earned', 'scholastic record',
                      'final grade', 'final grades', 'grading system', 'general weighted average', 'subject code', 'descriptive title'],
    'FTA'         => ['final teaching assignment', 'teaching assignment', 'teaching load', 'faculty load', 'fta', 'class schedule',
                      'no. of units', 'room', 'section', 'load units'],
    'IPCR'        => ['individual performance commitment and review', 'ipcr', 'performance commitment', 'success indicators',
                      'actual accomplishments', 'major final output', 'ratee', 'rater', 'final average rating'],
    'Contract'    => ['contract of service', 'contract of services', 'first party', 'second party', 'witnesseth',
                      'contractor', 'terms and conditions', 'part-time', 'part time'],
    'Affidavit'   => ['affidavit of undertaking', 'affidavit', 'undertaking', 'affiant', 'subscribed and sworn', 'undertake'],
    'Other'       => ['memorandum', 'memo', 'notice', 'promotion', 'special order', 'office order', 'notice of salary adjustment'],
]);

// Confidence check on the auto-categorization (Fig. 5 "confident?"). The
// classifier's confidence is 0-1 (see OcrProcessor::confidence()); at or
// above this the detected category is pre-selected on the upload form,
// below it the faculty member must pick the category themselves and the
// upload is listed for the Admin in Classification Review.
define('CONFIDENCE_THRESHOLD', 0.60);

// How long after uploading a faculty member can still delete the document
// themselves (a wrong file or a duplicate). After that only the Admin can
// archive or delete it. Hours; the check is in document_action.php.
define('FACULTY_DELETE_WINDOW_HOURS', 24);

// Auto-archive (auto_archive_old_documents() in includes/functions.php): a
// document whose own date is more than this many years ago moves to its
// owner's archive. The document's date is its seminar / training end date,
// else its start date, else its date issued, else the upload date. Runs at
// most once a day on dashboard load (and from cron/auto_archive.php), and
// right after a document is uploaded or its dates are edited.
define('ARCHIVE_AFTER_YEARS', 5);
// Categories never auto-archived, e.g. ['Diploma', 'TOR'] to keep degrees
// and transcripts in the active 201 file however old they are. Empty = the
// rule applies to every category.
define('ARCHIVE_EXEMPT_CATEGORIES', []);

// Seminar / training details recorded for certificates (upload form,
// Edit Details, Seminar & Training Report). Add values here as needed.
define('TRAINING_TYPES', ['Seminar', 'Training', 'Workshop', 'Webinar', 'Conference', 'Symposium', 'Forum', 'Other']);
define('TRAINING_LEVELS', ['Local', 'Regional', 'National', 'International']);

// Profile pictures (profile.php): JPG / PNG only, cropped to a square and
// resized to PROFILE_PICTURE_SIZE pixels, stored in the database.
define('PROFILE_PICTURE_MAX_BYTES', 2 * 1024 * 1024); // 2MB
define('PROFILE_PICTURE_SIZE', 400);

// Brute-force login protection (login_process.php). Failures are counted
// over the last FAILED_ATTEMPT_WINDOW_MINUTES; reaching a limit refuses
// further logins for LOCKOUT_MINUTES, even with the right password.
// Per email entered (whether or not the account exists, so a lock doesn't
// reveal that), and per IP address with a higher limit so a shared campus
// network isn't easily blocked. A successful login resets the email's count.
define('MAX_FAILED_ATTEMPTS', 5);
define('MAX_IP_FAILED_ATTEMPTS', 20);
define('FAILED_ATTEMPT_WINDOW_MINUTES', 15);
define('LOCKOUT_MINUTES', 15);
// Warn "N attempts left" once only this many remain (0 = never say)
define('WARN_REMAINING_ATTEMPTS', 2);

// Subtype hints, tried once the main category is known. The first
// subtype with the most hits wins; if none match, the category's
// fallback subtype (see document_categories()) is used.
define('DOCUMENT_SUBTYPE_KEYWORDS', [
    'Certificate' => [
        'Seminar'  => ['seminar', 'webinar', 'symposium', 'conference', 'forum', 'lecture', 'convention', 'summit'],
        'Training' => ['training', 'workshop', 'course', 'bootcamp', 'certificate of completion', 'hands-on'],
    ],
    'Diploma' => [
        'Doctorate' => ['doctor of philosophy', 'doctorate', 'doctor of', 'ph.d', 'phd', 'ed.d', 'd.i.t'],
        'Master'    => ['master of', 'masters', 'master in', 'm.a.', 'm.s.'],
        'Bachelor'  => ['bachelor of', 'bachelor in', 'baccalaureate'],
    ],
    'Other' => [
        'Memo'      => ['memorandum', 'memo'],
        'Notice'    => ['notice'],
        'Promotion' => ['promotion', 'promoted', 'reclassification', 'appointment'],
    ],
]);

// PDS Section VI (Learning and Development) rows that fit on the official
// CS Form No. 212 (Revised 2026): 17 on page 3 (sheet C3), then 44 per
// continuation sheet C5. Extra entries always go on further C5 sheets.
define('PDS_LD_ROWS_PAGE3', 17);
define('PDS_LD_ROWS_CONTINUATION', 44);

// Colleges and their programs. A faculty member / Program Chair belongs to
// one program; a Dean to one college. Upload notifications go only to the
// Program Chair of the uploader's program and the Dean of their college.
// Keys are stored in users.college / users.program -- add programs here.
define('COLLEGES', [
    'CCS' => 'College of Computing Studies',
]);
define('PROGRAMS', [
    'BSCS' => ['label' => 'BS Computer Science', 'college' => 'CCS'],
    'BSIT' => ['label' => 'BS Information Technology', 'college' => 'CCS'],
]);

// Path to the tesseract binary. On XAMPP/Windows this is usually the full
// path to tesseract.exe; on macOS/Linux with Tesseract installed via
// brew/apt it is typically just "tesseract" (must be on PATH).
define('TESSERACT_BINARY_PATH', 'tesseract');

// Python with OpenCV for ocr/docscan.py (cropping / straightening photos of
// documents). The Docker image installs it in /opt/docscan; elsewhere the
// system python3 is tried, and uploads work without it (no auto-crop).
define('DOCSCAN_PYTHON', getenv('DOCSCAN_PYTHON') ?: (is_file('/opt/docscan/bin/python') ? '/opt/docscan/bin/python' : 'python3'));

// Error display. Errors are always logged; they are only shown in the
// browser when APP_DEBUG=1, or on local XAMPP (no APP_BASE_URL set).
// Anywhere else a user sees a plain message -- never paths, line
// numbers, stack traces or database errors.
define('APP_DEBUG', getenv('APP_DEBUG') !== false ? getenv('APP_DEBUG') === '1' : getenv('APP_BASE_URL') === false);
error_reporting(E_ALL);
ini_set('log_errors', '1');
ini_set('display_errors', APP_DEBUG ? '1' : '0');
if (!APP_DEBUG) {
    set_exception_handler(function (Throwable $e) {
        error_log('Uncaught ' . get_class($e) . ': ' . $e->getMessage() . ' in ' . $e->getFile() . ':' . $e->getLine());
        if (!headers_sent()) { http_response_code(500); header('Content-Type: text/html; charset=UTF-8'); }
        echo '<!DOCTYPE html><meta charset="UTF-8"><title>Something went wrong</title>'
           . '<div style="font-family:system-ui,sans-serif;max-width:480px;margin:15vh auto;padding:0 16px;text-align:center">'
           . '<h2>Something went wrong</h2><p>Please try again in a moment. If the problem continues, contact the administrator.</p>'
           . '<p><a href="' . htmlspecialchars(BASE_URL, ENT_QUOTES) . '/index.php">Back to the home page</a></p></div>';
    });
}

session_start();
