<?php
/**
 * Renders pages of the official PDS (CS Form No. 212, Revised 2026) from
 * the templates generated by tools/build_pds_template.php.
 *
 * Each template is the sheet's print area converted cell-for-cell. Empty
 * cells are {{REF}} placeholders and checkboxes {{chk:REF}} (REF = the
 * checkbox's linked cell in the workbook). A page is laid out exactly as
 * Excel prints it: Long bond paper (8.5" x 13"), the sheet's own margins, fit-to-page (or fixed)
 * scale rounded down to a whole percent like Excel, and centering.
 */

const PDS_FORM_DIR = __DIR__ . '/pds_form';
const PDS_PAPER_IN = [8.5, 13];   // Long / Folio bond, 8.5" x 13" (612 x 936 pt), portrait

function pds_form_meta(): array {
    static $meta = null;
    if ($meta === null) {
        $meta = json_decode(file_get_contents(PDS_FORM_DIR . '/sheets.json'), true);
    }
    return $meta;
}

/** CSS for all PDS pages: page box + generated cell/font styles. */
function pds_form_css(): string {
    $base = <<<CSS
@page { size: 8.5in 13in; margin: 0; }
.pds-page { width: 8.5in; height: 13in; position: relative; overflow: hidden; background: #fff;
            page-break-after: always; break-after: page; }
.pds-page:last-child { page-break-after: auto; break-after: auto; }
.pds-page .xl-frame { position: absolute; }
.pds-page .xl-sheet { position: absolute; left: 0; top: 0; }
table.xl { border-collapse: collapse; table-layout: fixed; }
table.xl td { padding: 0; position: relative; vertical-align: top; }
/* letter-spacing: Chrome sets Arial Narrow ~1% wider than Excel; this keeps line breaks identical */
.xl .c { position: absolute; inset: 0; z-index: 1; display: flex; box-sizing: border-box; padding: 0 2px; line-height: 1.15; letter-spacing: -0.005em; }
.xl .c > span { flex: none; }            /* unwrapped text keeps its width and spills over neighbours like Excel */
.xl .c.w > span { flex: none; width: 100%; }
.xl .c .val { color: #000; }
.xl .c .val.spill { position: absolute; left: 3px; top: 50%; transform: translateY(-50%); white-space: nowrap; }  /* runs across the empty cells to its right */
.xl .c .val.fit { display: block; overflow: hidden; white-space: normal; overflow-wrap: anywhere; }
.xl-chk { position: absolute; display: flex; align-items: center; gap: 5px; white-space: nowrap; line-height: 1; }
.xl-chk i { width: 9px; height: 9px; border: calc(1.05px / var(--z, 1)) solid #000; flex: none; position: relative; background: #fff; margin-left: 2px; }
.xl-chk i.on::after { content: ''; position: absolute; left: 2.5px; top: -1px; width: 3px; height: 7px;
                      border: solid #000; border-width: 0 1.6px 1.6px 0; transform: rotate(40deg); }
.xl-drop { position: absolute; }
.xl-drop b { position: absolute; right: 0; top: 2px; bottom: 2px; width: 22px; background: #f0f0f0; border-left: 1px solid #d0d0d0; }
.xl-drop b::after { content: ''; position: absolute; left: 4px; top: 50%; margin-top: -3px;
                    border: 5px solid transparent; border-top: 6px solid #000; border-bottom: 0; }
.xl-line { position: absolute; height: 0; border-top: calc(1.05px / var(--z, 1)) solid #000; }
.xl-box { position: absolute; box-sizing: border-box; border: calc(1.05px / var(--z, 1)) solid #000; background: #fff; display: flex; align-items: center;
          justify-content: center; font-family: Arial, sans-serif; line-height: 1.15; z-index: 2; }
.xl-box > div { width: 100%; }
.xl-box p { margin: 0; }
.xl-photo { position: absolute; object-fit: cover; }
CSS;
    return $base . "\n" . file_get_contents(PDS_FORM_DIR . '/pds_form.css');
}

/** Excel's print scale for a sheet (fit-to-page is rounded down to a whole percent). */
function pds_form_scale(array $m): float {
    if (!$m['fit']) { return $m['zoom'] / 100; }
    $pw = (PDS_PAPER_IN[0] - $m['margins']['left'] - $m['margins']['right']) * 96;
    $ph = (PDS_PAPER_IN[1] - $m['margins']['top'] - $m['margins']['bottom']) * 96;
    $s = 1.0;
    if ($m['fitW'] > 0) { $s = min($s, $pw / $m['width']); }
    if ($m['fitH'] > 0) { $s = min($s, $ph / $m['height']); }
    return floor($s * 100) / 100;
}

/**
 * One printed page.
 * @param string $key     sheet key: C1 ... C11
 * @param array  $values  cell ref => text (e.g. ['D10' => 'DELA CRUZ'])
 * @param array  $checks  checkbox linked cell => true (e.g. ['D16' => true])
 * @param array  $images  [['src' => url, 'x' => px, 'y' => px, 'w' => px, 'h' => px]] placed over the sheet
 */
function pds_form_page(string $key, array $values = [], array $checks = [], array $images = []): string {
    $m = pds_form_meta()[$key];
    $html = file_get_contents(PDS_FORM_DIR . "/sheets/$key.html");
    $html = preg_replace('/^<!--.*?-->\s*/s', '', $html);
    $html = preg_replace_callback('/\{\{(chk:)?([A-Z]+\d+)\}\}/', function ($mm) use ($values, $checks, $m) {
        if ($mm[1]) { return !empty($checks[$mm[2]]) ? 'on' : ''; }
        $v = $values[$mm[2]] ?? '';
        $spill = is_array($v) && !empty($v['spill']);
        $text = is_array($v) ? (string)($v['text'] ?? '') : (string)$v;
        if ($text === '') { return ''; }
        $text = htmlspecialchars($text, ENT_QUOTES, 'UTF-8');
        if ($spill) { return '<span class="val spill">' . $text . '</span>'; }
        // Keep the value inside its own box (wrapping, never shrunk): like an
        // Excel cell whose neighbour is filled, it doesn't run into the next column.
        $cell = $m['cells'][$mm[2]] ?? null;
        $box = $cell ? sprintf('width:%dpx;max-height:%dpx', max(1, $cell['w'] - 4), max(1, $cell['h'] - 1)) : '';
        return '<span class="val fit" style="' . $box . '">' . $text . '</span>';
    }, $html);
    if ($images) {
        $imgs = '';
        foreach ($images as $im) {
            $imgs .= '<img class="xl-photo" src="' . htmlspecialchars($im['src']) . '" alt="" style="left:' . $im['x'] . 'px;top:' . $im['y']
                   . 'px;width:' . $im['w'] . 'px;height:' . $im['h'] . 'px">';
        }
        $html = preg_replace('/<\/div>\s*$/', $imgs . '</div>', $html);
    }

    $s = pds_form_scale($m);
    $pw = (PDS_PAPER_IN[0] - $m['margins']['left'] - $m['margins']['right']) * 96;
    $ph = (PDS_PAPER_IN[1] - $m['margins']['top'] - $m['margins']['bottom']) * 96;
    $left = $m['margins']['left'] * 96 + ($m['hCenter'] ? max(0, ($pw - $m['width'] * $s) / 2) : 0);
    $top  = $m['margins']['top'] * 96 + ($m['vCenter'] ? max(0, ($ph - $m['height'] * $s) / 2) : 0);
    $html = preg_replace('/^<div class="xl-sheet" style="/', '<div class="xl-sheet" style="zoom:' . sprintf('%.4f', $s) . ';--z:' . sprintf('%.4f', $s) . ';', $html, 1);
    // zoom (unlike transform) scales the layout box too, so print never shrinks the page to fit;
    // the frame just positions it within the page margins.
    $frame = sprintf('left:%.2fpx;top:%.2fpx;width:%.2fpx;height:%.2fpx', $left, $top, $m['width'] * $s, $m['height'] * $s);

    return '<section class="pds-page" data-sheet="' . $key . '"><div class="xl-frame" style="' . $frame . '">' . $html . '</div></section>';
}
